name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
      # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
      # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata for docker
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: dylanmccarthy/chronic_fatigue_utils
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
